import "./globals.css";
import Providers from "./provider";
import "react-toastify/dist/ReactToastify.css";
import { ToastContainer } from "react-toastify";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Navbar from "../components/navbar";
import Footer from "../components/footer";
import StoreProvider from "@/providers/store.provider";
import { PersistGate } from "redux-persist/integration/react";

const inter = Inter({ subsets: ["latin-ext"] });

export const metadata: Metadata = {
  title: {
    template: "%s",
    default: "Home", // a default is required when creating a template
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-[#f4f4f4]`}>
        <ToastContainer />
        <Providers>
          <StoreProvider>
            <Navbar />
            {children}
            <Footer />
          </StoreProvider>
        </Providers>
      </body>
    </html>
  );
}
